version: '{branch}-{build}'
image: Visual Studio 2015
clone_folder: C:\projects\oiio
test: off
configuration:
    - Release
    # - Debug
platform:
    - x64
# branches:
#   only:
#     - master
environment:
  matrix:
    - CMAKE_PLATFORM: "Visual Studio 14 2015 Win64"
      PYTHON_DIR: "C:\\Python27-x64"
      tbs_arch: "x64"
      tbs_tools: "msvc14"
      tbs_static_runtime: 0

cache:
  - C:\tools\vcpkg\installed
  #- C:\tools\vcpkg -> appveyor.yml
  #- C:\projects\ext -> appveyor.yml
  # The -> means that the cache dir is discarded if appveyor.yml has changed

install:
  - cinstall: python
  - git submodule update --init --recursive
  - set CMAKE_PREFIX_PATH=C:/Sys;%APPVEYOR_BUILD_FOLDER%/ext;c:/tools/vcpkg/installed/%platform%-windows
  - set CMAKE_LIBRARY_PATH=C:/Sys/lib;%APPVEYOR_BUILD_FOLDER%/ext/lib
  - set CMAKE_INCLUDE_PATH=C:/Sys/include;%APPVEYOR_BUILD_FOLDER%/ext/include
  - mkdir c:\sys
  - mkdir ext
  - cd ext
  - mkdir lib
  - mkdir include

  # Boost
  # 1.63 is already installed on appveyor, just use it
  - set BOOST_ROOT=C:\Libraries\boost_1_63_0
  - set CMAKE_PREFIX_PATH=%CMAKE_PREFIX_PATH%;%BOOST_ROOT%

  - vcpkg list
  - vcpkg update
  # - vcpkg help triplet

  - vcpkg install zlib:"%platform%"-windows
  - vcpkg install tiff:"%platform%"-windows
  - vcpkg install libpng:"%platform%"-windows
  - vcpkg install openexr:"%platform%"-windows
  - vcpkg install freetype:"%platform%"-windows
  - vcpkg install giflib:"%platform%"-windows
  - vcpkg install libraw:"%platform%"-windows
  - vcpkg install libwebp:"%platform%"-windows
  - vcpkg install openjpeg:"%platform%"-windows
  - vcpkg install ptex:"%platform%"-windows
  - vcpkg install ffmpeg:"%platform%"-windows
  - vcpkg install qt5-base:"%platform%"-windows
  # - vcpkg install opencv:"%platform%"-windows

  # Wish list:
  #   OpenColorIO

  - cd ..
  - dir C:\Sys
  # - dir C:\Sys\include
  # - dir C:\Sys\lib
  - vcpkg list
  - dir c:\tools\vcpkg
  - dir c:\tools\vcpkg\installed\x64-windows
  - dir C:\projects\oiio\ext
  - dir C:\projects\oiio\ext\include
  - dir C:\projects\oiio\ext\lib


build_script:
  - echo Running cmake...
  - cd c:\projects\oiio
  - mkdir build
  - mkdir build\windows64
  - cd build\windows64
  - cmake -G "%CMAKE_PLATFORM%" -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake \
      -DPYTHON_INCLUDE_DIR:PATH=%PYTHON_DIR%/include -DPYTHON_LIBRARY:FILEPATH=%PYTHON_DIR%/libs/python27.lib -DPYTHON_EXECUTABLE:FILEPATH=%PYTHON_DIR%/python.exe -DCMAKE_LIBRARY_PATH=%CMAKE_LIBRARY_PATH% -DCMAKE_INCLUDE_PATH=%CMAKE_INCLUDE_PATH%  -DCMAKE_PREFIX_PATH=%CMAKE_PREFIX_PATH% -DOPENEXR_ROOT_DIR=C:\projects\oiio\ext -DVERBOSE=1 -DBUILD_MISSING_DEPS=1 ../..
  - dir c:\projects\oiio
  - dir c:\projects\oiio\build
  - dir c:\projects\oiio\build\windows64
  - cmake --build . --config %CONFIGURATION%


matrix:
    fast_finish: true
